### ISSUE TITLE
Python3: C locale leads to pip install failure

### ISSUE THREAD

**Issue by jamielennox** [gabrielfalcao/HTTPretty#108]
When running with LC_ALL=C (which we and i would assume others do in our CI environments) pip fails due to their being non-ascii characters in the string of the file. 

This appears to be coming from the ã in your name in the copyright header https://github.com/gabrielfalcao/HTTPretty/blob/master/setup.py#L5

This is the one triggering the problem around pip, but i'm not sure (and i'm not sure how to test) if changing that one would fix at least the install process or whether it would then trigger on every copyright header. 

```
[jlennox@dhcp-40-102 ~]$ mkvirtualenv httpretty --python /usr/bin/python3.3
Running virtualenv with interpreter /usr/bin/python3.3
Using base prefix '/usr'
New python executable in httpretty/bin/python3.3
Also creating executable in httpretty/bin/python
Installing Setuptools..............................................................................................................................................................................................................................done.
Installing Pip.....................................................................................................................................................................................................................................................................................................................................done.
(httpretty)[jlennox@dhcp-40-102 ~]$ export LC_ALL=C
(httpretty)[jlennox@dhcp-40-102 ~]$ pip install httpretty
Downloading/unpacking httpretty
  Downloading httpretty-0.7.0.tar.gz
  Running setup.py egg_info for package httpretty
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/jlennox/.virtualenvs/httpretty/lib64/python3.3/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 129: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/jlennox/.virtualenvs/httpretty/lib64/python3.3/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 129: ordinal not in range(128)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/jlennox/.virtualenvs/httpretty/build/httpretty
Storing complete log in /home/jlennox/.pip/pip.log
```

**Comment by brianhelba** [comment]
@gabrielfalcao I believe you can close this issue, as it was fixed by https://github.com/gabrielfalcao/HTTPretty/pull/109 .

**Comment by gabrielfalcao** [comment]
@brianhelba thanks
