### ISSUE TITLE
Having trouble writing binary data with moto/HTTPretty

### ISSUE THREAD

**Issue by snakescott** [gabrielfalcao/HTTPretty#148]
I'm trying to use moto, which uses HTTPretty under the covers. The code fails with the stack trace below. It seems like HTTPretty is always utf8 encoding the http body, but this is binary data.

```
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 805, in send
    self.sock.sendall(data)
  File "/Users/jacobscott/.virtualenvs/mototest/lib/python2.7/site-packages/httpretty/core.py", line 374, in sendall
    httpretty.historify_request(headers, body, False)
  File "/Users/jacobscott/.virtualenvs/mototest/lib/python2.7/site-packages/httpretty/core.py", line 859, in historify_request
    request = HTTPrettyRequest(headers, body)
  File "/Users/jacobscott/.virtualenvs/mototest/lib/python2.7/site-packages/httpretty/core.py", line 180, in __init__
    self.parsed_body = self.parse_request_body(self.body)
  File "/Users/jacobscott/.virtualenvs/mototest/lib/python2.7/site-packages/httpretty/core.py", line 211, in parse_request_body
    body = decode_utf8(body)
  File "/Users/jacobscott/.virtualenvs/mototest/lib/python2.7/site-packages/httpretty/utils.py", line 42, in decode_utf8
    s = s.decode("utf-8")
  File "/Users/jacobscott/.virtualenvs/mototest/lib/python2.7/encodings/utf_8.py", line 16, in decode
```

``` python
from boto.s3.connection import S3Connection
from boto.s3.key import Key
import urllib2, os
from moto import mock_s3

@mock_s3
def test():
    conn = S3Connection()
    bucket = conn.create_bucket('mybucket')
    k = Key(bucket)
    k.key = "test-key"
    img = urllib2.urlopen("http://2.gravatar.com/avatar/da78c690dae46e5a74a96a3f67c8ec1c")
    with open('tmp.png', 'w') as f:
        f.write(img.read())
    k.set_contents_from_filename('tmp.png')

test()
```

**Comment by aop** [comment]
Using httpretty==0.8.10 I still face the same issue.

This time the trace looks like this
```
Traceback (most recent call last):
  File "/home/oskari/koodaus/myproject/env/local/lib/python2.7/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/home/oskari/koodaus/myproject/env/local/lib/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "/home/oskari/koodaus/myproject/tests/mytest.py", line 42, in test_mytest
    s3_connection.create_bucket(self.s3_bucket_name)
  File "/home/oskari/koodaus/myproject/env/local/lib/python2.7/site-packages/boto/s3/connection.py", line 612, in create_bucket
    data=data)
  File "/home/oskari/koodaus/myproject/env/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/home/oskari/koodaus/myproject/env/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/home/oskari/koodaus/myproject/env/local/lib/python2.7/site-packages/boto/connection.py", line 944, in _mexe
    response = connection.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1049, in getresponse
    response = self.response_class(*args, **kwds)
  File "/home/oskari/koodaus/myproject/env/local/lib/python2.7/site-packages/boto/connection.py", line 390, in __init__
    http_client.HTTPResponse.__init__(self, *args, **kwargs)
  File "/usr/lib/python2.7/httplib.py", line 352, in __init__
    self.fp = sock.makefile('rb', 0)
  File "/home/oskari/koodaus/myproject/env/local/lib/python2.7/site-packages/httpretty/core.py", line 332, in makefile
    self._entry.fill_filekind(self.fd)
  File "/home/oskari/koodaus/myproject/env/local/lib/python2.7/site-packages/httpretty/core.py", line 601, in fill_filekind
    string_list.append('date: %s' % headers.pop('date'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)
```
