### ISSUE TITLE
HTTPretty fails to coexist with multiprocessing: core.py line 291: ValueError: too many values to unpack

### ISSUE THREAD

**Issue by smartkiwi** [gabrielfalcao/HTTPretty#188]
This code fails with exception in HTTPretty core.py 

```
  File "/Users/user/PycharmProjects/proj1/1.py", line 8, in test_multiprocess
    d = manager.dict()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/managers.py", line 667, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/managers.py", line 565, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/connection.py", line 169, in Client
    c = SocketClient(address)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/connection.py", line 304, in SocketClient
    s.connect(address)
  File "/Users/user/Envs/hadoop/lib/python2.7/site-packages/httpretty/core.py", line 291, in connect
    self._address = (self._host, self._port) = address
ValueError: too many values to unpack
Process SyncManager-1:
Traceback (most recent call last):
```

Test code

```
from moto import mock_s3
from multiprocessing import Process, Manager

@mock_s3
def test_multiprocess():
    manager = Manager()
    d = manager.dict()

    def f():
        d[1].append(4)
        print d

    d[1] = []
    p = Process(target=f)
    p.start()
    p.join()

test_multiprocess()
```

**Comment by gabrielfalcao** [comment]
This is an interesting problem to solve, but I'm also curious why you're using multiprocess within a test, sounds like a recipe for a flaky test 🤷‍♂

**Comment by gabrielfalcao** [comment]
the code has changed drastically since this PR was first open, I am not able to fix it, the test gets stuck :(

**Comment by gabrielfalcao** [comment]
can be solved with this code:

```python
manager = Manager()


@httpretty.activate
def test_multiprocess():
    d = manager.dict()

    def f():
        d[1].append(4)

    d[1] = []
    p = Process(target=f)
    p.start()
    p.join()

```
