### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by cgwaldman** [gabrielfalcao/HTTPretty#212]
Redis server is running on localhost.
Attempting to use "moto" library causes the following.  Moto devs suggested that this is a problem with httpretty and that I file an issue here.

x201:) python
Python 2.7.9 (default, Jan  1 2015, 11:07:23) 
[GCC 4.8.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import redis
>>> redis.from_url("redis:").keys()
[]
>>> import moto.s3
>>> moto.s3.mock_s3().start()
>>> redis.from_url("redis:").keys()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/redis/client.py", line 919, in keys
    return self.execute_command('KEYS', pattern)
  File "/usr/lib64/python2.7/site-packages/redis/client.py", line 564, in execute_command
    connection.send_command(*args)
  File "/usr/lib64/python2.7/site-packages/redis/connection.py", line 557, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/lib64/python2.7/site-packages/redis/connection.py", line 533, in send_packed_command
    self.connect()
  File "/usr/lib64/python2.7/site-packages/redis/connection.py", line 433, in connect
    sock = self._connect()
  File "/usr/lib64/python2.7/site-packages/redis/connection.py", line 477, in _connect
    sock.connect(socket_address)
  File "/usr/lib64/python2.7/site-packages/httpretty-0.8.3-py2.7.egg/httpretty/core.py", line 296, in connect
    self.truesock.connect(self._address)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
TypeError: coercing to Unicode: need string or buffer, NoneType found
>>> 
>>>

**Comment by cgwaldman** [comment]
I've decided not to use HTTPretty/moto due to the monkey-patching of the  socket module causing too many other problems.

**Comment by JackDanger** [comment]
After finding folks choosing to avoid the use of Moto and HTTPretty due to the socket monkey-patching (and finding myself unable to do so) I decided to bypass HTTPretty just inside my Redis/Memcached clients. Here's how I did it:

```
    class BypassHTTPretty():
        def __enter__(self):
            self.reenable_later = httpretty.is_enabled()
            if httpretty.is_enabled():
                httpretty.disable()

        def __exit__(self, type, value, traceback):
            if self.reenable_later:
                httpretty.enable()

    def redis_set(key, value):
        with BypassHTTPretty():
          redis.set(key, value)
```
