### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by macnibblet** [gabrielfalcao/HTTPretty#214]
Python 3.4.0

```
(env)$ pip install httpretty
Downloading/unpacking httpretty
  Downloading httpretty-0.8.4.tar.gz (40kB): 40kB downloaded
  Running setup.py (path:/opt/env/build/httpretty/setup.py) egg_info for package httpretty
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/opt/env/build/httpretty/setup.py", line 86, in <module>
        version=read_version(),
      File "/opt/env/build/httpretty/setup.py", line 46, in read_version
        finder.visit(ast.parse(local_file('httpretty', '__init__.py')))
      File "/opt/env/build/httpretty/setup.py", line 78, in <lambda>
        open(os.path.join(os.path.dirname(__file__), *f)).read()
      File "/opt/env/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/opt/env/build/httpretty/setup.py", line 86, in <module>

    version=read_version(),

  File "/opt/env/build/httpretty/setup.py", line 46, in read_version

    finder.visit(ast.parse(local_file('httpretty', '__init__.py')))

  File "/opt/env/build/httpretty/setup.py", line 78, in <lambda>

    open(os.path.join(os.path.dirname(__file__), *f)).read()

  File "/opt/env/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)
```

**Comment by citizen-stig** [comment]
+1

**Comment by christopher-abastar** [comment]
+1

**Comment by Lobosque** [comment]
+1

**Comment by christopher-abastar** [comment]
Hello,

Not sure if this helps but I managed to fix it by doing some update on the environment variables.

```sh
LANG=en_US.UTF-8 
LC_CTYPE=en_US.UTF-8
```

**Comment by ibillett** [comment]
The above worked fine for me
