### ISSUE TITLE
Python3: httpretty fails to install if LANG=C environment variable is set.

### ISSUE THREAD

**Issue by JohnVillalovos** [gabrielfalcao/HTTPretty#224]
$ export LANG=C
$ pip install httpretty
Collecting httpretty
  Using cached httpretty-0.8.7.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-tvkn7au8/httpretty/setup.py", line 86, in <module>
        version=read_version(),
      File "/tmp/pip-build-tvkn7au8/httpretty/setup.py", line 46, in read_version
        finder.visit(ast.parse(local_file('httpretty', '__init__.py')))
      File "/tmp/pip-build-tvkn7au8/httpretty/setup.py", line 78, in <lambda>
        open(os.path.join(os.path.dirname(__file__), *f)).read()
      File "/home/jlvillal/openstack/python-ironicclient/venv/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-tvkn7au8/httpretty/setup.py", line 86, in <module>
    
        version=read_version(),
    
      File "/tmp/pip-build-tvkn7au8/httpretty/setup.py", line 46, in read_version
    
        finder.visit(ast.parse(local_file('httpretty', '__init__.py')))
    
      File "/tmp/pip-build-tvkn7au8/httpretty/setup.py", line 78, in <lambda>
    
        open(os.path.join(os.path.dirname(__file__), *f)).read()
    
      File "/home/jlvillal/openstack/python-ironicclient/venv/lib/python3.4/encodings/ascii.py", line 26, in decode
    
        return codecs.ascii_decode(input, self.errors)[0]
    
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-tvkn7au8/httpretty

**Comment by JohnVillalovos** [comment]
This appears to be a dup of #223
