### ISSUE TITLE
failures in testsuite under py3 in current httpretty-0.8.0, others for py2.7

### ISSUE THREAD

**Issue by idella** [gabrielfalcao/HTTPretty#236]
under py2.7 I get mass failures in test_requests.py to do with handshaking

``` python

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0-python2_7/lib/httpretty/core.py", line 1013, in wrapper
    return test(*args, **kw)
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0/tests/functional/test_requests.py", line 542, in test_httpretty_allows_to_chose_if_querystring_should_be_matched
    response = requests.get('https://example.org/what/')
  File "/usr/lib64/python2.7/site-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/usr/lib64/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib64/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib64/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib64/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [Errno bad handshake] (32, 'EPIPE')
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): example.org
--------------------- >> end captured logging << ---------------------
```

for a number of tests in test_requests.py:  6 of them:

``` bash
=======================================
ERROR: tests.functional.test_requests.
=======================================

test_httpretty_allows_to_chose_if_querystring_should_be_matched
test_httpretty_provides_easy_access_to_querystrings_with_regexes
test_httpretty_should_allow_registering_regexes
test_httpretty_should_allow_registering_regexes_and_give_a_proper_match_to_the_callback
test_httpretty_should_allow_registering_regexes_with_streaming_responses
test_py26_callback_response
```

under py3.3;

``` bash
======================================================================
ERROR: tests.unit.test_core.test_fakesock_socket_sendall_with_body_data_with_chunked_entry
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib64/python3.3/site-packages/mock.py", line 1210, in patched
    return func(*args, **keywargs)
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0/tests/unit/test_core.py", line 569, in test_fakesock_socket_sendall_with_body_data_with_chunked_entry
    socket.sendall(b"BLABLABLABLA")
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0-python3_3/lib/httpretty/core.py", line 365, in sendall
    headers = utf8(last_requestline(self._sent_data))
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0-python3_3/lib/httpretty/utils.py", line 37, in utf8
    return byte_type(s)
TypeError: 'NoneType' object is not iterable

======================================================================
ERROR: tests.unit.test_core.test_fakesock_socket_sendall_with_body_data_with_entry
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib64/python3.3/site-packages/mock.py", line 1210, in patched
    return func(*args, **keywargs)
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0/tests/unit/test_core.py", line 539, in test_fakesock_socket_sendall_with_body_data_with_entry
    socket.sendall(b"BLABLABLABLA")
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0-python3_3/lib/httpretty/core.py", line 365, in sendall
    headers = utf8(last_requestline(self._sent_data))
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0-python3_3/lib/httpretty/utils.py", line 37, in utf8
    return byte_type(s)
TypeError: 'NoneType' object is not iterable

======================================================================
FAIL: tests.unit.test_httpretty.test_httpretty_should_not_raise_on_socket_send_when_uri_not_registered
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/sure/__init__.py", line 777, in throw
    self.obj(*self._callable_args, **self._callable_kw)
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0-python3_3/lib/httpretty/core.py", line 420, in sendto
    return self.debug(self.truesock.sendto, *args, **kwargs)
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0-python3_3/lib/httpretty/core.py", line 411, in debug
    return func(*a, **kw)
TypeError: sendto() takes 2 or 3 arguments (0 given)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0/tests/unit/test_httpretty.py", line 96, in test_httpretty_should_not_raise_on_socket_send_when_uri_not_registered
    ).should_not.throw(RuntimeError)
  File "/usr/lib64/python3.3/site-packages/sure/__init__.py", line 375, in wrapper
    value = func(self, *args, **kw)
  File "/usr/lib64/python3.3/site-packages/sure/__init__.py", line 787, in throw
    raise AssertionError(err)
AssertionError: <bound method socket.sendto of <httpretty.core.fakesock.socket object at 0x7f8f09a688d0>> called with args [] and kwargs {} should not raise <class 'RuntimeError'> but raised sendto() takes 2 or 3 arguments (0 given)

======================================================================
FAIL: tests.unit.test_httpretty.test_global_boolean_enabled
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0/tests/unit/test_httpretty.py", line 239, in test_global_boolean_enabled
    expect(HTTPretty.is_enabled()).to.be.falsy
  File "/usr/lib64/python3.3/site-packages/sure/__init__.py", line 425, in __getattr__
    return getattr(self._ab, name)
  File "/usr/lib64/python3.3/site-packages/sure/__init__.py", line 375, in wrapper
    value = func(self, *args, **kw)
  File "/usr/lib64/python3.3/site-packages/sure/__init__.py", line 569, in falsy
    assert not bool(self.obj), msg
AssertionError: expected `True` to be falsy

======================================================================
FAIL: tests.unit.test_httpretty.test_fake_socket_passes_through_setblocking
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0/tests/unit/test_httpretty.py", line 280, in test_fake_socket_passes_through_setblocking
    s.truesock.setblocking.assert_called_with(0)
  File "/usr/lib64/python3.3/site-packages/mock.py", line 844, in assert_called_with
    raise AssertionError(msg)
AssertionError: Expected call: setblocking(0)
Actual call: setblocking()

======================================================================
FAIL: tests.unit.test_httpretty.test_fake_socket_passes_through_getsockopt
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0/tests/unit/test_httpretty.py", line 297, in test_fake_socket_passes_through_getsockopt
    s.truesock.getsockopt.assert_called_with(socket.SOL_SOCKET, 1)
  File "/usr/lib64/python3.3/site-packages/mock.py", line 844, in assert_called_with
    raise AssertionError(msg)
AssertionError: Expected call: getsockopt(1, 1)
Actual call: getsockopt()

======================================================================
FAIL: tests.unit.test_httpretty.test_fake_socket_passes_through_shutdown
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0/tests/unit/test_httpretty.py", line 353, in test_fake_socket_passes_through_shutdown
    s.truesock.shutdown.assert_called_with(socket.SHUT_RD)
  File "/usr/lib64/python3.3/site-packages/mock.py", line 844, in assert_called_with
    raise AssertionError(msg)
AssertionError: Expected call: shutdown(0)
Actual call: shutdown()

Coverage.py warning: No data was collected.
Name               Stmts   Miss  Cover   Missing
------------------------------------------------
httpretty             23     23     0%   26-56
httpretty.compat      10     10     0%   27-87
httpretty.core       535    535     0%   26-1020
httpretty.errors       3      3     0%   27-31
httpretty.http        28     28     0%   26-155
httpretty.utils       10     10     0%   26-44
------------------------------------------------
TOTAL                609    609     0%   
----------------------------------------------------------------------
Ran 84 tests in 1.490s

FAILED (errors=2, failures=5)
 * ERROR: dev-python/httpretty-0.8.0::gentoo failed (test phase):
 *   Tests failed under python3.3
```

Under py3.4 it hangs in a number of tests under the functional category or folder which may be related to issue 221.

**Comment by idella** [comment]
On removing tests/functional/test_requests.py all together; under python2.7;

```python
======================================================================
FAIL: tests.unit.test_httpretty.test_httpretty_should_not_raise_on_socket_send_when_uri_not_registered
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0-python2_7/tests/unit/test_httpretty.py", line 96, in test_httpretty_should_not_raise_on_socket_send_when_uri_not_registered
    ).should_not.throw(RuntimeError)
  File "/usr/lib64/python2.7/site-packages/sure/__init__.py", line 375, in wrapper
    value = func(self, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/sure/__init__.py", line 787, in throw
    raise AssertionError(err)
AssertionError: <bound method socket.sendto of <httpretty.core.socket object at 0x7f6abf099410>> called with args [] and kwargs {} should not raise <type 'exceptions.RuntimeError'> but raised sendto() takes 2 or 3 arguments (0 given)

======================================================================
FAIL: tests.unit.test_httpretty.test_global_boolean_enabled
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0-python2_7/tests/unit/test_httpretty.py", line 239, in test_global_boolean_enabled
    expect(HTTPretty.is_enabled()).to.be.falsy
  File "/usr/lib64/python2.7/site-packages/sure/__init__.py", line 425, in __getattr__
    return getattr(self._ab, name)
  File "/usr/lib64/python2.7/site-packages/sure/__init__.py", line 375, in wrapper
    value = func(self, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/sure/__init__.py", line 569, in falsy
    assert not bool(self.obj), msg
AssertionError: expected `True` to be falsy

======================================================================
FAIL: tests.unit.test_httpretty.test_fake_socket_passes_through_setblocking
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0-python2_7/tests/unit/test_httpretty.py", line 280, in test_fake_socket_passes_through_setblocking
    s.truesock.setblocking.assert_called_with(0)
  File "/usr/lib64/python2.7/site-packages/mock.py", line 844, in assert_called_with
    raise AssertionError(msg)
AssertionError: Expected call: setblocking(0)
Actual call: setblocking()

======================================================================
FAIL: tests.unit.test_httpretty.test_fake_socket_passes_through_getsockopt
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0-python2_7/tests/unit/test_httpretty.py", line 297, in test_fake_socket_passes_through_getsockopt
    s.truesock.getsockopt.assert_called_with(socket.SOL_SOCKET, 1)
  File "/usr/lib64/python2.7/site-packages/mock.py", line 844, in assert_called_with
    raise AssertionError(msg)
AssertionError: Expected call: getsockopt(1, 1)
Actual call: getsockopt()

======================================================================
FAIL: tests.unit.test_httpretty.test_fake_socket_passes_through_shutdown
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/httpretty-0.8.0/work/httpretty-0.8.0-python2_7/tests/unit/test_httpretty.py", line 353, in test_fake_socket_passes_through_shutdown
    s.truesock.shutdown.assert_called_with(socket.SHUT_RD)
  File "/usr/lib64/python2.7/site-packages/mock.py", line 844, in assert_called_with
    raise AssertionError(msg)
AssertionError: Expected call: shutdown(0)
Actual call: shutdown()

Coverage.py warning: No data was collected.
Name               Stmts   Miss  Cover   Missing
------------------------------------------------
httpretty             23     23     0%   26-56
httpretty.compat      10     10     0%   27-87
httpretty.core       535    535     0%   26-1020
httpretty.errors       3      3     0%   27-31
httpretty.http        28     28     0%   26-155
httpretty.utils       10     10     0%   26-44
------------------------------------------------
TOTAL                609    609     0%   
----------------------------------------------------------------------
Ran 82 tests in 0.628s

FAILED (failures=5)
```

2 issues with  sure;

exceptions.RuntimeError'> but raised sendto() takes 2 or 3 arguments (0 given 
in tests.unit.test_httpretty.test_httpretty_should_not_raise_on_socket_send_when_uri_not_registered
 and 3 with
/usr/lib64/python2.7/site-packages/mock.py
in the last 3.  I wonder if these are sensitive to a version of mock.
These all occur within tests of tests/unit.

**Comment by maanas** [comment]
+1
I m getting same errors in all my tests
https://travis-ci.org/agmscode/agms_python/jobs/59182990

**Comment by andrewgross** [comment]
Hey maanas, do you see these failures under python 2.7, or only 2.6.9?

**Comment by andrewgross** [comment]
@idella I know it has been a while since anyone has responded here, but do you still have this environment around?  I am curios if there were any other packages installed, especially related to SSL (like requests[security]).
