### ISSUE TITLE
httpretty breaks socket.accept() (fakesocket object does not support "_sock" kwarg)

### ISSUE THREAD

**Issue by memory** [gabrielfalcao/HTTPretty#239]
cf: https://github.com/spulec/moto/issues/330

Python's Socket.py _socketobject:

```
    185     def __init__(self, family=AF_INET, type=SOCK_STREAM, proto=0, _sock=None):
    186         if _sock is None:
    187             _sock = _realsocket(family, type, proto)
    188         self._sock = _sock
    189         for method in _delegate_methods:
    190             setattr(self, method, getattr(_sock, method))

    200
    201     def accept(self):
    202         sock, addr = self._sock.accept()
    203         return _socketobject(_sock=sock), addr
    204     accept.__doc__ = _realsocket.accept.__doc__
```

HTTPretty's core.py fakesock:

```
    245 class fakesock(object):
    246     class socket(object):
    247         _entry = None
    248         debuglevel = 0
    249         _sent_data = []
    250
    251         def __init__(self, family=socket.AF_INET, type=socket.SOCK_STREAM,
    252                      protocol=0):
```

This makes any program which attempts to call socket.accept() and pass in _sock throw TypeError, e.g.:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/vagrant/target/python/local/lib/python2.7/site-packages/werkzeug/serving.py", line 603, in inner
    passthrough_errors, ssl_context).serve_forever()
  File "/vagrant/target/python/local/lib/python2.7/site-packages/werkzeug/serving.py", line 462, in serve_forever
    HTTPServer.serve_forever(self)
  File "/usr/lib/python2.7/SocketServer.py", line 238, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    request, client_address = self.get_request()
  File "/vagrant/target/python/local/lib/python2.7/site-packages/werkzeug/serving.py", line 475, in get_request
    con, info = self.socket.accept()
  File "/usr/lib/python2.7/socket.py", line 203, in accept
    return _socketobject(_sock=sock), addr
TypeError: __init__() got an unexpected keyword argument '_sock'
```

**Comment by memory** [comment]
(FWIW: I've made a couple of attempts at fixing this myself, to no avail.  The initialization logic of fakesock.socket() vs _socketobject() is different enough, and I am not deeply familiar with the guts of python's socket support, that it wasn't immediately obvious to me what the proper implementation of accept() in a fakesocket object would be, and how to handle the _sock being passed in.)

**Comment by memory** [comment]
poke?

**Comment by SeanHayes** [comment]
Looks like this has been fixed:
https://github.com/gabrielfalcao/HTTPretty/commit/c813340b664fdd52635c143c7806f30441c0ab30#diff-a03c6fbc616fde95a9c4c55f1459ac48
