### ISSUE TITLE
Unable to install on Python3 if either LANG not set or specified locale not installed.

### ISSUE THREAD

**Issue by scraperdragon** [gabrielfalcao/HTTPretty#243]
Specifically, the `ã` in your name in `__init__.py` etc. causes `read()`ing from that file in `setup.py` to fail since it's not ASCII.

Leaving one or both of the lines commented below causes `pip3` to fail to install.
Uncommenting both makes it work successfully.

Dockerfile:
```Dockerfile
FROM ubuntu:14.04

RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y python3-pip

#RUN locale-gen en_GB.UTF-8

RUN mkdir /home/nobody && \
    chown nobody /home/nobody
USER nobody
ENV HOME=/home/nobody \
#    LANG=en_GB.UTF-8 \
    PATH=/home/nobody/.local/bin:$PATH
WORKDIR /home/nobody
```

```
nobody@4d4e2d0d4272:~$ pip3 install httpretty
Downloading/unpacking httpretty
  Downloading httpretty-0.8.8.tar.gz (40kB): 40kB downloaded
  Running setup.py (path:/tmp/pip_build_nobody/httpretty/setup.py) egg_info for package httpretty
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_nobody/httpretty/setup.py", line 86, in <module>
        version=read_version(),
      File "/tmp/pip_build_nobody/httpretty/setup.py", line 46, in read_version
        finder.visit(ast.parse(local_file('httpretty', '__init__.py')))
      File "/tmp/pip_build_nobody/httpretty/setup.py", line 78, in <lambda>
        open(os.path.join(os.path.dirname(__file__), *f)).read()
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_nobody/httpretty/setup.py", line 86, in <module>

    version=read_version(),

  File "/tmp/pip_build_nobody/httpretty/setup.py", line 46, in read_version

    finder.visit(ast.parse(local_file('httpretty', '__init__.py')))

  File "/tmp/pip_build_nobody/httpretty/setup.py", line 78, in <lambda>

    open(os.path.join(os.path.dirname(__file__), *f)).read()

  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_nobody/httpretty
Storing debug log for failure in /home/nobody/.pip/pip.log
```

**Comment by bpicolo** [comment]
The default encoding for python3 is utf8, not to mention __init__ explicitly declares utf-8 encoding. You definitely need to have utf8 installed for python3 to work properly in general.

**Comment by deuxpi** [comment]
I have a UTF-8 locale properly set and I still get this error (in my case, a run of tox with a Python 3.4 environment).
