### ISSUE TITLE
socket.bind(('localhost', None)) gets broken

### ISSUE THREAD

**Issue by tarekziade** [gabrielfalcao/HTTPretty#247]
When HTTPretty is enabled, the bind() API is broken when you pass None as a port (which is valid in python 3.4). I get this problem in my tornado tests where moto is used.

Disabling HTTPretty after it has been enabled won't fix the issue. 

example

```
>>> from tornado.testing import bind_unused_port
>>> bind_unused_port()
(<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketType.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 30335)>, 30335)
>>> from httpretty import HTTPretty
>>> HTTPretty.enable()
>>> bind_unused_port()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tarek/Dev/github.com/loads-broker2/lib/python3.4/site-packages/tornado/testing.py", line 89, in bind_unused_port
    [sock] = netutil.bind_sockets(None, 'localhost', family=socket.AF_INET)
  File "/Users/tarek/Dev/github.com/loads-broker2/lib/python3.4/site-packages/tornado/netutil.py", line 187, in bind_sockets
    sock.bind(sockaddr)
TypeError: an integer is required (got type NoneType)
>>> HTTPretty.disable()
>>> bind_unused_port()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tarek/Dev/github.com/loads-broker2/lib/python3.4/site-packages/tornado/testing.py", line 89, in bind_unused_port
    [sock] = netutil.bind_sockets(None, 'localhost', family=socket.AF_INET)
  File "/Users/tarek/Dev/github.com/loads-broker2/lib/python3.4/site-packages/tornado/netutil.py", line 160, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/socket.py", line 123, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
TypeError: an integer is required (got type socket)
```
Version: Tornado 4.2, Python 3.4.0, Mac OSX, HTTPretty latest release

**Comment by tarekziade** [comment]
Also, the socket init misses fileno in its constructor

**Comment by czanier** [comment]
Any news about this?
