### ISSUE TITLE
httpretty.activate does not play nice with nose_parameterized

### ISSUE THREAD

**Issue by cdown** [gabrielfalcao/HTTPretty#259]
I'm not sure of the technical reason, but using both of them seems to totally skip the test.

Test case:

```
import httpretty
from nose_parameterized import parameterized

@httpretty.activate
@parameterized([
    'foo',
    'bar',
])
def test_foo(bar):
    assert False
```

This test still passes when running `nosetests`, but I have no idea why. It seems it never actually runs the function body:

```
% nosetests -v
test.test_foo ... ok

----------------------------------------------------------------------
Ran 1 test in 0.030s

OK
```

Putting the `.activate` decorator below the `parameterized` decorator makes the test now fail:

```
% nosetests -v
test.test_foo('foo',) ... FAIL
test.test_foo('bar',) ... FAIL

======================================================================
FAIL: test.test_foo('foo',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chris/.virtualenvs/base/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/chris/.virtualenvs/base/lib/python3.4/site-packages/httpretty/core.py", line 1063, in wrapper
    return test(*args, **kw)
  File "/tmp/test/test.py", line 10, in test_foo
    assert False
AssertionError

======================================================================
FAIL: test.test_foo('bar',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chris/.virtualenvs/base/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/chris/.virtualenvs/base/lib/python3.4/site-packages/httpretty/core.py", line 1063, in wrapper
    return test(*args, **kw)
  File "/tmp/test/test.py", line 10, in test_foo
    assert False
AssertionError

----------------------------------------------------------------------
Ran 2 tests in 0.029s

FAILED (failures=2)
```

```
% pip freeze | awk '/httpretty/ || /param/'
httpretty==0.8.10
nose-parameterized==0.5.0
```

**Comment by gabrielfalcao** [comment]
I believe the problem is with parameterized, I've had it giving me false-positive results even without using httpretty.

I'm closing this old issue but feel free to reopen if you want to help debugging this
