### ISSUE TITLE
UnicodeDecodeError while trying to install

### ISSUE THREAD

**Issue by Lobosque** [gabrielfalcao/HTTPretty#263]
This happens on a docker (1.7.1) container using python 3.4.3 and pip 1.5.4:
I did set LANG and LC_ALL to en_US.UTF-8 but it didn't change anything

```
Downloading/unpacking httpretty==0.8.10 (from -r /srv/backend/requirements.txt (line 31))
  Running setup.py (path:/tmp/pip_build_root/httpretty/setup.py) egg_info for package httpretty
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/httpretty/setup.py", line 86, in <module>
        version=read_version(),
      File "/tmp/pip_build_root/httpretty/setup.py", line 46, in read_version
        finder.visit(ast.parse(local_file('httpretty', '__init__.py')))
      File "/tmp/pip_build_root/httpretty/setup.py", line 78, in <lambda>
        open(os.path.join(os.path.dirname(__file__), *f)).read()
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/httpretty/setup.py", line 86, in <module>

    version=read_version(),

  File "/tmp/pip_build_root/httpretty/setup.py", line 46, in read_version

    finder.visit(ast.parse(local_file('httpretty', '__init__.py')))

  File "/tmp/pip_build_root/httpretty/setup.py", line 78, in <lambda>

    open(os.path.join(os.path.dirname(__file__), *f)).read()

  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)
```

**Comment by dimazest** [comment]
same problem with anaconda build environment

https://anaconda.org/dimazest/httpretty/builds/15/1#L287

**Comment by seanlaw** [comment]
I am having the same problem. Not sure how httpretty comes into play here.

**Comment by bdewilde** [comment]
Same problem while building docs through readthedocs for a package with httppretty as a dependency:

```
Collecting httpretty==0.8.10 (from smart-open>=1.2.1->gensim->-r requirements.txt (line 7))
  Downloading httpretty-0.8.10.tar.gz (41kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-clbjw8vx/httpretty/setup.py", line 86, in <module>
        version=read_version(),
      File "/tmp/pip-build-clbjw8vx/httpretty/setup.py", line 46, in read_version
        finder.visit(ast.parse(local_file('httpretty', '__init__.py')))
      File "/tmp/pip-build-clbjw8vx/httpretty/setup.py", line 78, in <lambda>
        open(os.path.join(os.path.dirname(__file__), *f)).read()
      File "/home/docs/checkouts/readthedocs.org/user_builds/textacy/envs/latest/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)
```

**Comment by demidovakatya** [comment]
same error while trying to install gensim

```
Collecting gensim
  Using cached gensim-0.12.4-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.0 in /usr/local/lib/python3.5/site-packages (from gensim)
Collecting smart-open>=1.2.1 (from gensim)
  Using cached smart_open-1.3.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.3 in /usr/local/lib/python3.5/site-packages (from gensim)
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.7.0 in /usr/local/lib/python3.5/site-packages (from gensim)
Collecting boto>=2.32 (from smart-open>=1.2.1->gensim)
  Using cached boto-2.40.0-py2.py3-none-any.whl
Collecting httpretty==0.8.10 (from smart-open>=1.2.1->gensim)
  Using cached httpretty-0.8.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4d/3nptb4zs131fhwpblh5p21500000gn/T/pip-build-44fmc_vd/httpretty/setup.py", line 86, in <module>
        version=read_version(),
      File "/private/var/folders/4d/3nptb4zs131fhwpblh5p21500000gn/T/pip-build-44fmc_vd/httpretty/setup.py", line 46, in read_version
        finder.visit(ast.parse(local_file('httpretty', '__init__.py')))
      File "/private/var/folders/4d/3nptb4zs131fhwpblh5p21500000gn/T/pip-build-44fmc_vd/httpretty/setup.py", line 78, in <lambda>
        open(os.path.join(os.path.dirname(__file__), *f)).read()
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)
```

**Comment by dargueta-work** [comment]
Also happening on Travis running Python 3.5.1 when installing moto 0.4.25 with pip, httppretty 0.8.10.

```
ERROR -- : Collecting httpretty==0.8.10 (from moto==0.4.25->-r /data/clover_pipeline/requirements.txt (line 13))
ERROR -- :   Downloading httpretty-0.8.10.tar.gz (41kB)
ERROR -- :     Complete output from command python setup.py egg_info:
ERROR -- :     Traceback (most recent call last):
ERROR -- :       File "<string>", line 1, in <module>
ERROR -- :       File "/tmp/pip-build-xo36n0tw/httpretty/setup.py", line 86, in <module>
ERROR -- :         version=read_version(),
ERROR -- :       File "/tmp/pip-build-xo36n0tw/httpretty/setup.py", line 46, in read_version
ERROR -- :         finder.visit(ast.parse(local_file('httpretty', '__init__.py')))
ERROR -- :       File "/tmp/pip-build-xo36n0tw/httpretty/setup.py", line 78, in <lambda>
ERROR -- :         open(os.path.join(os.path.dirname(__file__), *f)).read()
ERROR -- :       File "/usr/local/lib/python3.5/encodings/ascii.py", line 26, in decode
ERROR -- :         return codecs.ascii_decode(input, self.errors)[0]
ERROR -- :     UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)
ERROR -- :
ERROR -- :     ----------------------------------------
ERROR -- : Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xo36n0tw/httpretty/
```
