### ISSUE TITLE
Unable to install httpretty-0.8.11 with pip

### ISSUE THREAD

**Issue by miknight** [gabrielfalcao/HTTPretty#273]
Using pip 7.1.2 with Python 2.7:
```
$ pip install httpretty
Collecting httpretty
  Downloading httpretty-0.8.11.tar.gz (43kB)
    100% |████████████████████████████████| 45kB 340kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/49/9_0w6jk90gs5cs1mfg27xn0w0000gn/T/pip-build-ByAPva/httpretty/setup.py", line 98, in <module>
        tests_require=parse_requirements('development.txt'),
      File "/private/var/folders/49/9_0w6jk90gs5cs1mfg27xn0w0000gn/T/pip-build-ByAPva/httpretty/setup.py", line 62, in parse_requirements
        raise RuntimeError("Couldn't find the `requirements.txt' file :(")
    RuntimeError: Couldn't find the `requirements.txt' file :(

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/49/9_0w6jk90gs5cs1mfg27xn0w0000gn/T/pip-build-ByAPva/httpretty
```

**Comment by miknight** [comment]
Raised https://github.com/gabrielfalcao/HTTPretty/pull/274 to address this.

**Comment by christopher-abastar** [comment]
currently experiencing this issue. Is the fix gonna be ready soon?

**Comment by tuukkamustonen** [comment]
Also bumped into this and keenly waiting for a fixed release.

**Comment by sebastianneubauer** [comment]
+1

**Comment by sebastianneubauer** [comment]
@gabrielfalcao : would you mind to delete this corrupted release from pypi as soon as possible? Would be quite some effort to (temporarily) limit all dependencies to httpretty<0.8.11 in all my projects using httpretty...

**Comment by wbolster** [comment]
deleting a release is not necessary and generally considered a wrong approach. a new fixed release would solve everything.

**Comment by bchatelard** [comment]
:+1:

**Comment by sebastianneubauer** [comment]
sure, a fixed release is fine as well, it' s just, if fixing takes 1h and removing 5min, I would love to have the corrupted package removed first and later a fixed release as soon as it is available...

**Comment by gabrielfalcao** [comment]
sorry guys, I'm in Brazil, the timezone is a bit off.
Thanks for your patience

**Comment by gabrielfalcao** [comment]
```bash
$  pip install -U httpretty
DEPRECATION: --download-cache has been deprecated and will be removed in the future. Pip now automatically uses and configures its cache.
Collecting httpretty
  Downloading httpretty-0.8.12.tar.gz (43kB)
    100% |████████████████████████████████| 45kB 239kB/s
Building wheels for collected packages: httpretty
  Running setup.py bdist_wheel for httpretty
  Stored in directory: /Users/gabrielfalcao/Library/Caches/pip/wheels/2b/bb/14/45417c4860e21e2268eced5511998762806e4d31924d58b056
Successfully built httpretty
Installing collected packages: httpretty
  Found existing installation: httpretty 0.8.10
    Uninstalling httpretty-0.8.10:
      Successfully uninstalled httpretty-0.8.10
Successfully installed httpretty-0.8.12
```

**Comment by sebastianneubauer** [comment]
thanks!
