### ISSUE TITLE
incompatibility with docker-py - _socketobject' object has no attribute '_host'

### ISSUE THREAD

**Issue by dtenenba** [gabrielfalcao/HTTPretty#311]
If I call the [docker-py API](https://github.com/docker/docker-py) while inside a function decorated with `@httpretty.activate`, I get an error. To reproduce you will need to install docker and then `pip install docker-py`. 

Code:

```python
import httpretty
import docker

@httpretty.activate
def test_example():
    client = docker.Client()
    images = client.images()

test_example()
```

Produces the stack trace below.
This is with 

```
$ pip freeze |grep pretty
httpretty==0.8.14
```

I originally posted this as an [issue](https://github.com/spulec/moto/issues/749) against `moto` because I hadn't tried to reproduce it with httpretty alone. 

Can this be fixed? I am dead in the water until it is. 
Unfortunately the function I want to test uses both docker and AWS (endpoints that I want to mock) so short of a major refactor of my code, I can't work around this.

Here is the stack trace:

```
Traceback (most recent call last):
  File "t.py", line 9, in <module>
    test_example()
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/httpretty-0.8.14-py2.7.egg/httpretty/core.py", line 1240, in wrapper
    return test(*args, **kw)
  File "t.py", line 7, in test_example
    images = client.images()
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/docker/api/image.py", line 40, in images
    res = self._result(self._get(self._url("/images/json"), params=params),
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/docker/client.py", line 132, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 869, in send
    self.sock.sendall(data)
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/httpretty-0.8.14-py2.7.egg/httpretty/core.py", line 487, in sendall
    hostname=self._host,
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/httpretty-0.8.14-py2.7.egg/httpretty/core.py", line 544, in __getattr__
    return getattr(self.truesock, name)
AttributeError: '_socketobject' object has no attribute '_host'
```

**Comment by dtenenba** [comment]
If anyone else runs into this, I came up with a hacky workaround. It's not ideal because it means I have to change the code under test because of this issue.

I do this:

```python
import docker
import httpretty


@contextmanager
def turn_httpretty_off():
    if httpretty.is_enabled():
        httpretty.disable()
    yield
    if not httpretty.is_enabled():
        httpretty.enable()

```

Then later in the function I want to test:

```python
def some_function_that_calls_web_services_and_uses_docker():
    # call web services here (tests will mock the endpoints)
    with turn_httpretty_off():
        # do stuff with docker here
    # call more web services
```
