### ISSUE TITLE
Python 3.7 test failures (SSL related)

### ISSUE THREAD

**Issue by hroncok** [gabrielfalcao/HTTPretty#337]
https://travis-ci.org/hroncok/HTTPretty/jobs/381122886

```
   AssertionError: Traceback (most recent call last):
     File "/opt/python/3.7-dev/lib/python3.7/urllib/request.py", line 1316, in do_open
       encode_chunked=req.has_header('Transfer-encoding'))
     File "/opt/python/3.7-dev/lib/python3.7/http/client.py", line 1229, in request
       self._send_request(method, url, body, headers, encode_chunked)
     File "/opt/python/3.7-dev/lib/python3.7/http/client.py", line 1275, in _send_request
       self.endheaders(body, encode_chunked=encode_chunked)
     File "/opt/python/3.7-dev/lib/python3.7/http/client.py", line 1224, in endheaders
       self._send_output(message_body, encode_chunked=encode_chunked)
     File "/opt/python/3.7-dev/lib/python3.7/http/client.py", line 1016, in _send_output
       self.send(msg)
     File "/opt/python/3.7-dev/lib/python3.7/http/client.py", line 977, in send
       self.sock.sendall(data)
     File "/opt/python/3.7-dev/lib/python3.7/ssl.py", line 987, in sendall
       return socket.sendall(self, data, flags)
   BrokenPipeError: [Errno 32] Broken pipe
   
   During handling of the above exception, another exception occurred:
   
   Traceback (most recent call last):
     File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/sure/__init__.py", line 186, in wrap
       func(start, *args, **kw)
     File "/home/travis/build/hroncok/HTTPretty/tests/functional/test_urllib2.py", line 191, in test_httpretty_should_support_a_list_of_successive_responses_urllib2
       request1 = urlopen('https://api.yahoo.com/test')
     File "/opt/python/3.7-dev/lib/python3.7/urllib/request.py", line 222, in urlopen
       return opener.open(url, data, timeout)
     File "/opt/python/3.7-dev/lib/python3.7/urllib/request.py", line 525, in open
       response = self._open(req, data)
     File "/opt/python/3.7-dev/lib/python3.7/urllib/request.py", line 543, in _open
       '_open', req)
     File "/opt/python/3.7-dev/lib/python3.7/urllib/request.py", line 503, in _call_chain
       result = func(*args)
     File "/opt/python/3.7-dev/lib/python3.7/urllib/request.py", line 1359, in https_open
       context=self._context, check_hostname=self._check_hostname)
     File "/opt/python/3.7-dev/lib/python3.7/urllib/request.py", line 1318, in do_open
       raise URLError(err)
```

https://travis-ci.org/hroncok/HTTPretty/jobs/381122887

```
   Traceback (most recent call last):
    /home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/nose/case.py line 198 in runTest
      self.test(*self.arg)
    httpretty/core.py line 1631 in wrapper
      return test(*args, **kw)
    tests/pyopenssl/test_mock.py line 42 in test_httpretty_overrides_when_pyopenssl_installed
      response = requests.get('https://yipit.com')
    /home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/requests/api.py line 72 in get
      return request('get', url, params=params, **kwargs)
    /home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/requests/api.py line 58 in request
      return session.request(method=method, url=url, **kwargs)
    /home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/requests/sessions.py line 508 in request
      resp = self.send(prep, **send_kwargs)
    /home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/requests/sessions.py line 618 in send
      r = adapter.send(request, **kwargs)
    /home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/requests/adapters.py line 506 in send
      raise SSLError(e, request=request)
   SSLError: HTTPSConnectionPool(host='yipit.com', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError("wildcard can only be present in the leftmost segment: '*yipit.com'")))
```

Also with Python 3.7.0b4 on Fedora:

```
AssertionError: Traceback (most recent call last):
     File "/home/churchyard/Dokumenty/RedHat/HTTPretty/.tox/py37/lib/python3.7/site-packages/sure/__init__.py", line 186, in wrap
       func(start, *args, **kw)
     File "/home/churchyard/Dokumenty/RedHat/HTTPretty/tests/functional/test_httplib2.py", line 278, in test_callback_response
       'https://api.yahoo.com/test', 'GET')
     File "/home/churchyard/Dokumenty/RedHat/HTTPretty/.tox/py37/lib/python3.7/site-packages/httplib2/__init__.py", line 1514, in request
       (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
     File "/home/churchyard/Dokumenty/RedHat/HTTPretty/.tox/py37/lib/python3.7/site-packages/httplib2/__init__.py", line 1264, in _request
       (response, content) = self._conn_request(conn, request_uri, method, body, headers)
     File "/home/churchyard/Dokumenty/RedHat/HTTPretty/.tox/py37/lib/python3.7/site-packages/httplib2/__init__.py", line 1187, in _conn_request
       conn.connect()
     File "/home/churchyard/Dokumenty/RedHat/HTTPretty/.tox/py37/lib/python3.7/site-packages/httplib2/__init__.py", line 1013, in connect
       self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
     File "/usr/lib64/python3.7/ssl.py", line 412, in wrap_socket
       session=session
     File "/usr/lib64/python3.7/ssl.py", line 817, in _create
       super(SSLSocket, self).__init__(**kwargs)
   TypeError: super(type, obj): obj must be an instance or subtype of type
```

But fallbacks to broken pipe above if I do crazy changes in SSLSocket from the stdlib.

cc @tiran because I have no idea what's going on here.

**Comment by tiran** [comment]
The root cause of the issue is inside the exception chain, although a bit hard to spot:

> ``SSLError(CertificateError("wildcard can only be present in the leftmost segment: '*yipit.com'"))``

Starting with Python 3.7, partial wild card matching is no longer supported. Browsers have removed support for partial wild cards a while ago. See https://docs.python.org/3.7/library/ssl.html#ssl.match_hostname and https://docs.python.org/3.7/whatsnew/3.7.html#ssl

**Comment by hroncok** [comment]
Also the difference between a2+ (Travis) and b4 (Fedora) Fedora is here I guess:

https://github.com/python/cpython/pull/5864

I was able to hack around back to the broken pipe when replacing SSLSocked with cls in the `super(SSLSocket, self).__init__(**kwargs)` call.

**Comment by tiran** [comment]
@hroncok what are ``cls`` and ``self`` in the ``_create`` call? Is there some monkey-patching involved?

**Comment by hroncok** [comment]
There is monkey-patching involved. It's ssl.SSLSocket but with different id. I guess it comes from

https://github.com/gabrielfalcao/HTTPretty/blob/cdfc5622ab9515cefabdc64fd39ed7b472ba5f38/httpretty/core.py#L311

**Comment by tiran** [comment]
Yeah, that's not supported. ``SSLContext.wrap_socket()`` only supports subclasses of ``SSLSocket``.

**Comment by hroncok** [comment]
Also another interesting failures are in cloud-init tests:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/httpretty/core.py", line 1319, in wrapper
    return test(*args, **kw)
  File "/builddir/build/BUILD/cloud-init-17.1/tests/unittests/test_datasource/test_openstack.py", line 136, in test_successful
    _register_uris(self.VERSION, EC2_FILES, EC2_META, OS_FILES)
  File "/builddir/build/BUILD/cloud-init-17.1/tests/unittests/test_datasource/test_openstack.py", line 124, in _register_uris
    body=get_request_callback)
  File "/usr/lib/python3.7/site-packages/httpretty/core.py", line 1124, in register_uri
    match_querystring, priority)
  File "/usr/lib/python3.7/site-packages/httpretty/core.py", line 877, in __init__
    self.info = URIInfo.from_uri(uri, entries)
  File "/usr/lib/python3.7/site-packages/httpretty/core.py", line 844, in from_uri
    result = urlsplit(uri)
  File "/usr/lib64/python3.7/urllib/parse.py", line 400, in urlsplit
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "/usr/lib64/python3.7/urllib/parse.py", line 123, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "/usr/lib64/python3.7/urllib/parse.py", line 107, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "/usr/lib64/python3.7/urllib/parse.py", line 107, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
AttributeError: 're.Pattern' object has no attribute 'decode'
```

**Comment by hroncok** [comment]
I am working on this and I think I've got it covered.

**Comment by hroncok** [comment]
See https://github.com/gabrielfalcao/HTTPretty/pull/339

**Comment by hroncok** [comment]
PR merged

**Comment by elafontaine** [comment]
This seems to have broken the SSL compatibility with Python 2.7.8 

___________ ERROR collecting <private>\test_utils.py:6: in <module>
   import httpretty
<private>\lib\site-packages\httpretty\__init__.py:28: in <module>
   from . import core
<private>\lib\site-packages\httpretty\core.py:102: in <module>
   old_sslcontext_wrap_socket = ssl.SSLContext.wrap_socket
E   AttributeError: 'module' object has no attribute 'SSLContext'
_____________ ERROR collecting tests/tasks/test_runtimecleanup.py _____________
<private test file>: in <module>
   import httpretty
<private>\lib\site-packages\httpretty\__init__.py:28: in <module>
   from . import core
<private>\lib\site-packages\httpretty\core.py:102: in <module>
   old_sslcontext_wrap_socket = ssl.SSLContext.wrap_socket
E   AttributeError: 'module' object has no attribute 'SSLContext'

Is it something that could be fixed easily and still allow support for 2.7?

**Comment by hroncok** [comment]
But we can definitively only do it on Python 3.

**Comment by elafontaine** [comment]
@hroncok  Anything that could be done to wrap the call on line 102 to take a default value of None?  Would that works?

**Comment by elafontaine** [comment]
That would be awesome!

**Comment by hroncok** [comment]
@elafontaine Does https://github.com/gabrielfalcao/HTTPretty/pull/341 help?

**Comment by elafontaine** [comment]
Should this be done in another issue?  How do you want to proceed?

I'm sorry, I just don't know the process and I don't know what to expect as delays and if I should watch this thread or a new thread.  If you could share some information in that regards, I would appreciate it :).

👍 for answering extra quickly though :).

**Comment by elafontaine** [comment]
I'll try it :)

**Comment by elafontaine** [comment]
when it passes though :p

**Comment by elafontaine** [comment]
Technical problems... I can't pull your commit XD sorry

**Comment by elafontaine** [comment]
Ok, so I was able to make my tests pass with your commit :).

This would fix the old version of python 2.7

**Comment by elafontaine** [comment]
Are you able to specify a specific python 2 version in the test matrix?  if that would be the case, you could add 2.7.8 and it would make the coverage pass :).

**Comment by hroncok** [comment]
Not really.

>
