### ISSUE TITLE
Tests inside docker fail

### ISSUE THREAD

**Issue by WisdomPill** [gabrielfalcao/HTTPretty#366]
I moved my project to docker and all the tests with httpretty.activate decorator fail with the following output 
```
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 141, in _read_from_self
    data = self._ssock.recv(4096)
  File "/usr/local/lib/python3.6/dist-packages/httpretty/core.py", line 497, in recv
    return self.debug('recv', *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/httpretty/core.py", line 476, in debug
    return getattr(self.truesock, truesock_func)(*a, **kw)
OSError: [Errno 22] Invalid argument
```

**Comment by tmbo** [comment]
I am running into the same issue when our tests are run on travis. Any idea where this might be coming from?

**Comment by gabrielfalcao** [comment]
could you please share the full code to reproduce the issue?

**Comment by nesies** [comment]
Here is a simple test, which is ok on VM and KO on docker (gitlab/runner)

CentOS 7
```
yum install -y python3-pip
cat > requirements.txt << EOF
httpretty==1.0.2
requests==2.24.0
unittest-xml-reporting==2.5.2
EOF

pip3 install -r requirements.txt

```
```
import requests


class A:
    def get(self):
        a = requests.get(
            "http://www.google.com/bad_url",
            timeout=3)

        return a.status_code, a.text

```

```
import httpretty
import unittest


from a import A


class TestA(unittest.TestCase):
    @httpretty.activate
    def test0(self):
        httpretty.register_uri(
            httpretty.GET,
            "http://www.google.com/bad_url",
            body="html",
            status=200,
            content_type="application/json"
        )

        a = A()
        code, text = a.get()
        self.assertEqual(code, 200)
        self.assertEqual(text, "html")


if __name__ == '__main__':
    unittest.main()

```


```$ python3 test_a.py
E
======================================================================
ERROR: test0 (__main__.TestA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='proxy.kube.int.nbyt.fr', port=3100): Max retries exceeded with url: http://www.google.com/bad_url (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/httpretty/core.py", line 1861, in wrapper
    return test(*args, **kw)
  File "test_a.py", line 23, in test0
    code, text = a.get()
  File "/builds/FASEISEN/zabbix2snow/a.py", line 11, in get
    timeout=3)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='proxy.kube.int.nbyt.fr', port=3100): Max retries exceeded with url: http://www.google.com/bad_url (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
----------------------------------------------------------------------
Ran 1 test in 0.022s
FAILED (errors=1)

```

**Comment by nesies** [comment]
by the way, i found that i have http_proxy environ variables defined in docker but not in the my dev machine.

#122
