### ISSUE TITLE
HTTPretty asks me to open an issue and paste the following traceback

### ISSUE THREAD

**Issue by ozooxo** [gabrielfalcao/HTTPretty#367]
Although I am not sure what is happening, I am following the suggestions:

```
Traceback (most recent call last):
  ... ...
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1438, in set_contents_from_string
    encrypt_key=encrypt_key)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1305, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 762, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 963, in _send_file_internal
    query_args=query_args
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 671, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 803, in sender
    http_conn.endheaders()
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 873, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python2.7/dist-packages/moto/packages/httpretty/core.py", line 434, in sendall
    self.real_sendall(data)
  File "/usr/local/lib/python2.7/dist-packages/moto/packages/httpretty/core.py", line 374, in real_sendall
    received = self.truesock.recv(self._bufsize)
  File "/usr/local/lib/python2.7/dist-packages/httpretty/core.py", line 595, in recv
    return self.debug('recv', *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/httpretty/core.py", line 571, in debug
    raise RuntimeError("\n".join(message))
RuntimeError: HTTPretty intercepted and unexpected socket method call.
Please open an issue at 'https://github.com/gabrielfalcao/HTTPretty/issues'
And paste the following traceback:

['  File "/usr/local/bin/nosetests", line 11, in <module>\n    sys.exit(run_exit())\n', '  File "/usr/local/lib/python2.7/dist-packages/nose/core.py", line 121, in __init__\n    **extra_args)\n', '  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__\n    self.runTests()\n', '  File "/usr/local/lib/python2.7/dist-packages/nose/core.py", line 207, in runTests\n    result = self.testRunner.run(self.test)\n', '  File "/usr/local/lib/python2.7/dist-packages/nose/core.py", line 62, in run\n    test(result)\n', '  File "/usr/local/lib/python2.7/dist-packages/nose/suite.py", line 177, in __call__\n    return self.run(*arg, **kw)\n', '  File "/usr/local/lib/python2.7/dist-packages/nose/suite.py", line 224, in run\n    test(orig)\n', '  File "/usr/local/lib/python2.7/dist-packages/nose/suite.py", line 177, in __call__\n    return self.run(*arg, **kw)\n', '  File "/usr/local/lib/python2.7/dist-packages/nose/suite.py", line 224, in run\n    test(orig)\n', '  File "/usr/local/lib/python2.7/dist-packages/nose/suite.py", line 177, in __call__\n    return self.run(*arg, **kw)\n', '  File "/usr/local/lib/python2.7/dist-packages/nose/suite.py", line 224, in run\n    test(orig)\n', '  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 45, in __call__\n    return self.run(*arg, **kwarg)\n', '  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 133, in run\n    self.runTest(result)\n', '  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 151, in runTest\n    test(result)\n', '  File "/usr/lib/python2.7/unittest/case.py", line 393, in __call__\n    return self.run(*args, **kwds)\n', '  File "/var/peloton/api/lib/unittest.py", line 85, in taxes_patcher\n    return func(*args, **kwargs)\n', '  File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched\n    return func(*args, **keywargs)\n', '  File "/var/peloton/api/lib/unittest.py", line 128, in wrapper\n    result = func(*args, **kwargs)\n', '  File "/var/peloton/api/lib/unittest.py", line 148, in wrapper\n    result = func(instance, *args, **kwargs)\n', '  File "/var/peloton/api/lib/unittest.py", line 179, in wrapper\n    result = func(instance, *args, **kwargs)\n', '  File "/var/peloton/api/lib/unittest.py", line 102, in wrapper\n    result = func(*args, **kwargs)\n', '  File "/var/peloton/api/lib/unittest.py", line 348, in run\n    test_method()\n', '  File "/usr/local/lib/python2.7/dist-packages/timeout_decorator/timeout_decorator.py", line 81, in new_function\n    return function(*args, **kwargs)\n', '  File "/usr/local/lib/python2.7/dist-packages/moto/core/models.py", line 71, in wrapper\n    result = func(*args, **kwargs)\n', '  File "/var/peloton/api/tests/cms/app/server/controllers/test_instructors.py", line 692, in test_share_image_profile_get\n    image_url=\'image_url\'\n', '  File "/var/peloton/api/lib/orm/base/models.py", line 402, in save_with\n    return cls.new_with(id=id, save=True, **kwargs)\n', '  File "/var/peloton/api/lib/orm/base/models.py", line 394, in new_with\n    return cls._set_values(instance, save=save, **kwargs)\n', '  File "/var/peloton/api/lib/orm/base/models.py", line 382, in _set_values\n    setattr(instance, key, val)\n', '  File "/var/peloton/api/lib/orm/base/descriptors.py", line 843, in __set__\n    key.set_contents_from_string(value, headers=headers)\n', '  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1438, in set_contents_from_string\n    encrypt_key=encrypt_key)\n', '  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1305, in set_contents_from_file\n    chunked_transfer=chunked_transfer, size=size)\n', '  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 762, in send_file\n    chunked_transfer=chunked_transfer, size=size)\n', '  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 963, in _send_file_internal\n    query_args=query_args\n', '  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 671, in make_request\n    retry_handler=retry_handler\n', '  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request\n    retry_handler=retry_handler)\n', '  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 940, in _mexe\n    request.body, request.headers)\n', '  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 803, in sender\n    http_conn.endheaders()\n', '  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders\n    self._send_output(message_body)\n', '  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output\n    self.send(msg)\n', '  File "/usr/lib/python2.7/httplib.py", line 873, in send\n    self.sock.sendall(data)\n', '  File "/usr/local/lib/python2.7/dist-packages/moto/packages/httpretty/core.py", line 434, in sendall\n    self.real_sendall(data)\n', '  File "/usr/local/lib/python2.7/dist-packages/moto/packages/httpretty/core.py", line 374, in real_sendall\n    received = self.truesock.recv(self._bufsize)\n', '  File "/usr/local/lib/python2.7/dist-packages/httpretty/core.py", line 595, in recv\n    return self.debug(\'recv\', *args, **kwargs)\n', '  File "/usr/local/lib/python2.7/dist-packages/httpretty/core.py", line 562, in debug\n    lines = list(map(utf8, traceback.format_stack(frame)))\n']
```

**Comment by gabrielfalcao** [comment]
Hey @ozooxo can you share more details on how to reproduce?
If you could share at least some portion of your failing test would be great
