### ISSUE TITLE
tests.functional.test_requests.test_streaming_responses fail

### ISSUE THREAD

**Issue by eadwu** [gabrielfalcao/HTTPretty#374]
Test fails with `AssertionError: Iterating by char is taking forever!`. Full build log in NixOS for reference [1]. Extracted error is the following:

```
======================================================================
FAIL: tests.functional.test_requests.test_streaming_responses
Mock a streaming HTTP response, like those returned by the Twitter streaming
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/3s6lbjw0mglp1qd196h6hnjzw60mi38y-python2.7-nose-1.3.7/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/nix/store/3s6lbjw0mglp1qd196h6hnjzw60mi38y-python2.7-nose-1.3.7/lib/python2.7/site-packages/nose/util.py", line 620, in newfunc
    return func(*arg, **kw)
  File "/build/httpretty-0.9.6/httpretty/core.py", line 1702, in wrapper
    return test(*args, **kw)
  File "/nix/store/5xqqhlgsb13ii7w8876ihd8iy96g1gri-python2.7-sure-1.4.11/lib/python2.7/site-packages/sure/__init__.py", line 209, in wrap
    raise AssertionError(exc.pop(0))
AssertionError: Traceback (most recent call last):
  File "/nix/store/5xqqhlgsb13ii7w8876ihd8iy96g1gri-python2.7-sure-1.4.11/lib/python2.7/site-packages/sure/__init__.py", line 186, in wrap
    func(start, *args, **kw)
  File "/build/httpretty-0.9.6/tests/functional/test_requests.py", line 362, in test_streaming_responses
    twitter_body = b''.join(c for c in response.iter_content(chunk_size=1))
  File "/build/httpretty-0.9.6/tests/functional/test_requests.py", line 362, in <genexpr>
    twitter_body = b''.join(c for c in response.iter_content(chunk_size=1))
  File "/nix/store/mw7d04jda0qfn8a6kz8f2jvllkgz8608-python2.7-requests-2.20.1/lib/python2.7/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/nix/store/w07ciki5msskipkmj8frvlgrcw7ax07i-python2.7-urllib3-1.24.1/lib/python2.7/site-packages/urllib3/response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/nix/store/w07ciki5msskipkmj8frvlgrcw7ax07i-python2.7-urllib3-1.24.1/lib/python2.7/site-packages/urllib3/response.py", line 442, in read
    data = self._fp.read(amt)
  File "/nix/store/hr42fl2wlixsr9k3ycpqfkla5lpn6was-python-2.7.15/lib/python2.7/httplib.py", line 597, in read
    s = self.fp.read(amt)
  File "/build/httpretty-0.9.6/httpretty/core.py", line 319, in __getattr__
    def __getattr__(self, name):
  File "/build/httpretty-0.9.6/tests/functional/test_requests.py", line 302, in handler
    raise AssertionError(message)
AssertionError: Iterating by char is taking forever!


----------------------------------------------------------------------
```

[1] https://hydra.nixos.org/build/89035814/nixlog/1

**Comment by jpopelka** [comment]
+1

https://kojipkgs.fedoraproject.org//work/tasks/4303/36674303/build.log
