### ISSUE TITLE
Install failed to run `pip install httpretty==1.0.0`

### ISSUE THREAD

**Issue by akun** [gabrielfalcao/HTTPretty#397]
install failed

pip install httpretty==1.0.0

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-download-o5h2pebg/httpretty/setup.py", line 58, in <module>
        tests_require=local_file('development.txt').splitlines(),
      File "/tmp/pip-download-o5h2pebg/httpretty/setup.py", line 40, in <lambda>
        os.path.join(os.path.dirname(__file__), *f), encoding='utf-8').read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-download-o5h2pebg/httpretty/development.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by bartaz** [comment]
Same here. Our CI jobs started to fail because of that.

**Comment by laiyazhou** [comment]
same too

pip install httpretty==1.0.0  failed

pip install httpretty==0.9.7 success

**Comment by Nicusor97** [comment]
Same on my side. They forgot to include `development.txt` file into the tar.gz.

**Comment by codyd51** [comment]
Same here. Thanks to the maintainers for hopping on this so quickly!

**Comment by gabrielfalcao** [comment]
Very sorry about this problem folks, release 1.02 is out and fixes the problem, please create an issue if you have any problems and I'll try to fix ASAP.
