### ISSUE TITLE
ValueError: write to closed file when emulating timeouts

### ISSUE THREAD

**Issue by davetapley** [gabrielfalcao/HTTPretty#438]
I am emulating a timeout per [here](https://httpretty.readthedocs.io/en/latest/guides.html#emulating-timeouts), however when I use this approach with a `requests` [`timeout`](https://docs.python-requests.org/en/master/user/advanced/#timeouts) I get this error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vscode/.local/lib/python3.9/site-packages/httpretty/core.py", line 1133, in fill_filekind
    fk.write(utf8(item) + b'\n')
ValueError: write to closed file
```

---

I _assume_ it would be safe to just catch the `ValueError: write to closed file` in ⬇️   because it _should_ only happen when emulating a timeout in this way?
https://github.com/gabrielfalcao/HTTPretty/blob/a11874a04ded409dca6b1bacc2d7814b0d0addc2/httpretty/core.py#L1132-L1135

**Comment by gabrielfalcao** [comment]
Hey @davetapley, thanks for reporting this issue.

> I assume it would be safe to just catch the ValueError: write to closed file in ⬇️ because it should only happen when emulating a timeout in this way?
This could be a last resort, but first I would like to reproduce the issue and try to fix the root cause. 

Would you be able to share some piece of code to reproduce the issue?

**Comment by zhanyuanucb** [comment]
Got the same issue using the same example here: https://httpretty.readthedocs.io/en/latest/guides.html?highlight=timeout#emulating-timeouts

I'm using python3.11

Any follow up on this?

**Comment by jerrykan** [comment]
For anyone else who comes across this issue, I've worked around the issue be wrapping the `threading.excepthook` to suppress the exception:

```python
import threading

def _excepthook_wrapper():      
    _orig_excepthook = threading.excepthook      
      
    def _excepthook(args):      
        if isinstance(args.exc_value, ValueError) and args.exc_value.args == (
            'write to closed file',  
        ):    
            return      
      
        return _orig_excepthook(args)      
      
    return _excepthook      
      
      
# suppress exceptions in httpretty thread for timeout test      
threading.excepthook = _excepthook_wrapper()
```

Just place the above code somewhere before your tests run and it should help.
