### ISSUE TITLE
1.1.4: pytest is failing because missing `context` fixture

### ISSUE THREAD

**Issue by kloczek** [gabrielfalcao/HTTPretty#440]
I'm trying to package your module as an rpm package.
As in build procedure I'm executing pytest based test suite I have errores about missing `context` fixture.
Cannot figure out which one modole provides it.
May I ask for some help?
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-httpretty-1.1.4-3.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-httpretty-1.1.4-3.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra --ignore tests/bugfixes/nosetests/test_414_httpx.py
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
Using --randomly-seed=1673478214
rootdir: /home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, freezegun-0.4.2, aspectlib-1.5.2, toolbox-0.5, rerunfailures-9.1.1, requests-mock-1.9.3, cov-2.12.1, flaky-3.7.0, benchmark-3.4.1, xdist-2.3.0, pylama-7.7.1, datadir-1.3.1, regressions-2.2.0, cases-3.6.3, xprocess-0.18.1, black-0.3.12, anyio-3.3.0, asyncio-0.15.1, trio-0.7.0, subtests-0.5.0, isort-2.0.0, hypothesis-6.14.6, mock-3.6.1, profiling-1.7.0, randomly-3.8.0, Faker-8.12.1, nose2pytest-1.0.8, pyfakefs-4.5.1, tornado-0.8.1, twisted-1.13.3
collected 11153 items

tests/functional/test_urllib2.py ............                                                                                                                        [  0%]
tests/unit/test_httpretty.py .............................                                                                                                           [  0%]
tests/functional/test_httplib2.py ............                                                                                                                       [  0%]
tests/bugfixes/nosetests/test_416_boto3.py .                                                                                                                         [  0%]
tests/pyopenssl/test_mock.py .                                                                                                                                       [  0%]
tests/functional/test_decorator.py ......                                                                                                                            [  0%]
tests/functional/test_bypass.py E..EEE                                                                                                                               [  0%]
tests/unit/test_http.py .                                                                                                                                            [  0%]
tests/functional/test_debug.py EEEEE                                                                                                                                 [  0%]
tests/bugfixes/nosetests/test_242_ssl_bad_handshake.py .                                                                                                             [  0%]
tests/functional/test_passthrough.py ..                                                                                                                              [  0%]
tests/bugfixes/pytest/test_426_mypy_segfault.py .................................................................................................................... [  1%]
.................................................................................................................................................................... [  3%]
.................................................................................................................................................................... [  4%]
.................................................................................................................................................................... [  6%]
.................................................................................................................................................................... [  7%]
.................................................................................................................................................................... [  9%]
.................................................................................................................................................................... [ 10%]
.................................................................................................................................................................... [ 12%]
.................................................................................................................................................................... [ 13%]
.................................................................................................................................................................... [ 14%]
.................................................................................................................................................................... [ 16%]
.................................................................................................................................................................... [ 17%]
.................................................................................................................................................................... [ 19%]
.................................................................................................................................................................... [ 20%]
.................................................................................................................................................................... [ 22%]
.................................................................................................................................................................... [ 23%]
.................................................................................................................................................................... [ 25%]
.................................................................................................................................................................... [ 26%]
.................................................................................................................................................................... [ 28%]
.................................................................................................................................................................... [ 29%]
.................................................................................................................................................................... [ 31%]
.................................................................................................................................................................... [ 32%]
.................................................................................................................................................................... [ 34%]
.................................................................................................................................................................... [ 35%]
.................................................................................................................................................................... [ 37%]
.................................................................................................................................................................... [ 38%]
.................................................................................................................................................................... [ 39%]
.................................................................................................................................................................... [ 41%]
.................................................................................................................................................................... [ 42%]
.................................................................................................................................................................... [ 44%]
.................................................................................................................................................................... [ 45%]
.................................................................................................................................................................... [ 47%]
.................................................................................................................................................................... [ 48%]
.................................................................................................................................................................... [ 50%]
.................................................................................................................................................................... [ 51%]
.................................................................................................................................................................... [ 53%]
.................................................................................................................................................................... [ 54%]
.................................................................................................................................................................... [ 56%]
.................................................................................................................................................................... [ 57%]
.................................................................................................................................................................... [ 59%]
.................................................................................................................................................................... [ 60%]
.................................................................................................................................................................... [ 62%]
.................................................................................................................................................................... [ 63%]
.................................................................................................................................................................... [ 64%]
.................................................................................................................................................................... [ 66%]
.................................................................................................................................................................... [ 67%]
.................................................................................................................................................................... [ 69%]
.................................................................................................................................................................... [ 70%]
.................................................................................................................................................................... [ 72%]
.................................................................................................................................................................... [ 73%]
.................................................................................................................................................................... [ 75%]
.................................................................................................................................................................... [ 76%]
.................................................................................................................................................................... [ 78%]
.................................................................................................................................................................... [ 79%]
.................................................................................................................................................................... [ 81%]
.................................................................................................................................................................... [ 82%]
.................................................................................................................................................................... [ 84%]
.................................................................................................................................................................... [ 85%]
.................................................................................................................................................................... [ 87%]
.................................................................................................................................................................... [ 88%]
.................................................................................................................................................................... [ 89%]
.................................................................................................................................................................... [ 91%]
.................................................................................................................................................................... [ 92%]
.................................................................................................................................................................... [ 94%]
.................................................................................................................................................................... [ 95%]
.................................................................................................................................................................... [ 97%]
.................................................................................................................................................................... [ 98%]
............................................................                                                                                                         [ 99%]
tests/functional/test_requests.py ...........E........................                                                                                               [ 99%]
tests/bugfixes/nosetests/test_430_respect_timeout.py .                                                                                                               [ 99%]
tests/bugfixes/nosetests/test_388_unmocked_error_with_url.py .                                                                                                       [ 99%]
tests/bugfixes/nosetests/test_tornado_bind_unused_port.py s                                                                                                          [ 99%]
tests/bugfixes/nosetests/test_425_latest_requests.py .                                                                                                               [ 99%]
tests/unit/test_main.py ...                                                                                                                                          [ 99%]
tests/unit/test_core.py ..........................                                                                                                                   [ 99%]
tests/bugfixes/nosetests/test_413_regex.py ..                                                                                                                        [ 99%]
tests/bugfixes/nosetests/test_417_openssl.py ..                                                                                                                      [ 99%]
tests/bugfixes/nosetests/test_387_regex_port.py ..                                                                                                                   [ 99%]
tests/bugfixes/nosetests/test_eventlet.py .                                                                                                                          [ 99%]
tests/bugfixes/nosetests/test_redis.py s                                                                                                                             [100%]

================================================================================== ERRORS ==================================================================================
______________________________________________________________ ERROR at setup of test_disallow_net_connect_1 _______________________________________________________________
file /home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_bypass.py, line 164
  @httpretty.activate(allow_net_connect=False)
  @that_with_context(start_http_server, stop_http_server)
  def test_disallow_net_connect_1(context, verbose=True):
E       fixture 'context' not found
>       available fixtures: _session_faker, _unused_port, anyio_backend, anyio_backend_name, anyio_backend_options, autojump_clock, base_url, benchmark, benchmark_weave, betamax_parametrized_recorder, betamax_parametrized_session, betamax_recorder, betamax_session, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, cov, current_cases, data_regression, datadir, dataframe_regression, doctest_namespace, event_loop, faker, faker_seed, file_regression, freezer, fs, http_client, http_port, http_server, https_client, https_port, https_server, image_regression, io_loop, mock_clock, mocker, module_mocker, monkeypatch, no_cover, num_regression, nursery, original_datadir, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, requests_mock, session_mocker, shared_datadir, smart_caplog, subtests, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, tmpworkdir, twisted_greenlet, unused_tcp_port, unused_tcp_port_factory, virtualenv, weave, worker_id, workspace, xprocess
>       use 'pytest --fixtures [testpath]' for help on them.

/home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_bypass.py:164
_____________________________________________________ ERROR at setup of test_using_httpretty_with_other_tcp_protocols ______________________________________________________
file /home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_bypass.py, line 146
  @httpretty.activate(verbose=True)
  @that_with_context(start_tcp_server, stop_tcp_server)
  def test_using_httpretty_with_other_tcp_protocols(context):
E       fixture 'context' not found
>       available fixtures: _session_faker, _unused_port, anyio_backend, anyio_backend_name, anyio_backend_options, autojump_clock, base_url, benchmark, benchmark_weave, betamax_parametrized_recorder, betamax_parametrized_session, betamax_recorder, betamax_session, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, cov, current_cases, data_regression, datadir, dataframe_regression, doctest_namespace, event_loop, faker, faker_seed, file_regression, freezer, fs, http_client, http_port, http_server, https_client, https_port, https_server, image_regression, io_loop, mock_clock, mocker, module_mocker, monkeypatch, no_cover, num_regression, nursery, original_datadir, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, requests_mock, session_mocker, shared_datadir, smart_caplog, subtests, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, tmpworkdir, twisted_greenlet, unused_tcp_port, unused_tcp_port_factory, virtualenv, weave, worker_id, workspace, xprocess
>       use 'pytest --fixtures [testpath]' for help on them.

/home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_bypass.py:146
_____________________________________________________ ERROR at setup of test_httpretty_bypasses_a_unregistered_request _____________________________________________________
file /home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_bypass.py, line 123
  @httpretty.activate(verbose=True)
  @that_with_context(start_http_server, stop_http_server)
  def test_httpretty_bypasses_a_unregistered_request(context):
E       fixture 'context' not found
>       available fixtures: _session_faker, _unused_port, anyio_backend, anyio_backend_name, anyio_backend_options, autojump_clock, base_url, benchmark, benchmark_weave, betamax_parametrized_recorder, betamax_parametrized_session, betamax_recorder, betamax_session, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, cov, current_cases, data_regression, datadir, dataframe_regression, doctest_namespace, event_loop, faker, faker_seed, file_regression, freezer, fs, http_client, http_port, http_server, https_client, https_port, https_server, image_regression, io_loop, mock_clock, mocker, module_mocker, monkeypatch, no_cover, num_regression, nursery, original_datadir, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, requests_mock, session_mocker, shared_datadir, smart_caplog, subtests, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, tmpworkdir, twisted_greenlet, unused_tcp_port, unused_tcp_port_factory, virtualenv, weave, worker_id, workspace, xprocess
>       use 'pytest --fixtures [testpath]' for help on them.

/home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_bypass.py:123
_________________________________________________________ ERROR at setup of test_httpretty_bypasses_when_disabled __________________________________________________________
file /home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_bypass.py, line 89
  @httpretty.activate
  @that_with_context(start_http_server, stop_http_server)
  def test_httpretty_bypasses_when_disabled(context):
E       fixture 'context' not found
>       available fixtures: _session_faker, _unused_port, anyio_backend, anyio_backend_name, anyio_backend_options, autojump_clock, base_url, benchmark, benchmark_weave, betamax_parametrized_recorder, betamax_parametrized_session, betamax_recorder, betamax_session, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, cov, current_cases, data_regression, datadir, dataframe_regression, doctest_namespace, event_loop, faker, faker_seed, file_regression, freezer, fs, http_client, http_port, http_server, https_client, https_port, https_server, image_regression, io_loop, mock_clock, mocker, module_mocker, monkeypatch, no_cover, num_regression, nursery, original_datadir, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, requests_mock, session_mocker, shared_datadir, smart_caplog, subtests, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, tmpworkdir, twisted_greenlet, unused_tcp_port, unused_tcp_port_factory, virtualenv, weave, worker_id, workspace, xprocess
>       use 'pytest --fixtures [testpath]' for help on them.

/home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_bypass.py:89
_________________________________________________________ ERROR at setup of test_httpretty_debugs_socket_recv_into _________________________________________________________
file /home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_debug.py, line 72
  @skip('not currently supported')
  @httprettified
  @scenario(create_socket)
  def test_httpretty_debugs_socket_recv_into(context):
E       fixture 'context' not found
>       available fixtures: _session_faker, _unused_port, anyio_backend, anyio_backend_name, anyio_backend_options, autojump_clock, base_url, benchmark, benchmark_weave, betamax_parametrized_recorder, betamax_parametrized_session, betamax_recorder, betamax_session, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, cov, current_cases, data_regression, datadir, dataframe_regression, doctest_namespace, event_loop, faker, faker_seed, file_regression, freezer, fs, http_client, http_port, http_server, https_client, https_port, https_server, image_regression, io_loop, mock_clock, mocker, module_mocker, monkeypatch, no_cover, num_regression, nursery, original_datadir, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, requests_mock, session_mocker, shared_datadir, smart_caplog, subtests, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, tmpworkdir, twisted_greenlet, unused_tcp_port, unused_tcp_port_factory, virtualenv, weave, worker_id, workspace, xprocess
>       use 'pytest --fixtures [testpath]' for help on them.

/home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_debug.py:72
___________________________________________________________ ERROR at setup of test_httpretty_debugs_socket_send ____________________________________________________________
file /home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_debug.py, line 39
  @skip('not currently supported')
  @httprettified
  @scenario(create_socket)
  def test_httpretty_debugs_socket_send(context):
E       fixture 'context' not found
>       available fixtures: _session_faker, _unused_port, anyio_backend, anyio_backend_name, anyio_backend_options, autojump_clock, base_url, benchmark, benchmark_weave, betamax_parametrized_recorder, betamax_parametrized_session, betamax_recorder, betamax_session, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, cov, current_cases, data_regression, datadir, dataframe_regression, doctest_namespace, event_loop, faker, faker_seed, file_regression, freezer, fs, http_client, http_port, http_server, https_client, https_port, https_server, image_regression, io_loop, mock_clock, mocker, module_mocker, monkeypatch, no_cover, num_regression, nursery, original_datadir, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, requests_mock, session_mocker, shared_datadir, smart_caplog, subtests, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, tmpworkdir, twisted_greenlet, unused_tcp_port, unused_tcp_port_factory, virtualenv, weave, worker_id, workspace, xprocess
>       use 'pytest --fixtures [testpath]' for help on them.

/home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_debug.py:39
_________________________________________________________ ERROR at setup of test_httpretty_debugs_socket_recvfrom __________________________________________________________
file /home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_debug.py, line 61
  @skip('not currently supported')
  @httprettified
  @scenario(create_socket)
  def test_httpretty_debugs_socket_recvfrom(context):
E       fixture 'context' not found
>       available fixtures: _session_faker, _unused_port, anyio_backend, anyio_backend_name, anyio_backend_options, autojump_clock, base_url, benchmark, benchmark_weave, betamax_parametrized_recorder, betamax_parametrized_session, betamax_recorder, betamax_session, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, cov, current_cases, data_regression, datadir, dataframe_regression, doctest_namespace, event_loop, faker, faker_seed, file_regression, freezer, fs, http_client, http_port, http_server, https_client, https_port, https_server, image_regression, io_loop, mock_clock, mocker, module_mocker, monkeypatch, no_cover, num_regression, nursery, original_datadir, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, requests_mock, session_mocker, shared_datadir, smart_caplog, subtests, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, tmpworkdir, twisted_greenlet, unused_tcp_port, unused_tcp_port_factory, virtualenv, weave, worker_id, workspace, xprocess
>       use 'pytest --fixtures [testpath]' for help on them.

/home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_debug.py:61
__________________________________________________________ ERROR at setup of test_httpretty_debugs_socket_sendto ___________________________________________________________
file /home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_debug.py, line 50
  @skip('not currently supported')
  @httprettified
  @scenario(create_socket)
  def test_httpretty_debugs_socket_sendto(context):
E       fixture 'context' not found
>       available fixtures: _session_faker, _unused_port, anyio_backend, anyio_backend_name, anyio_backend_options, autojump_clock, base_url, benchmark, benchmark_weave, betamax_parametrized_recorder, betamax_parametrized_session, betamax_recorder, betamax_session, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, cov, current_cases, data_regression, datadir, dataframe_regression, doctest_namespace, event_loop, faker, faker_seed, file_regression, freezer, fs, http_client, http_port, http_server, https_client, https_port, https_server, image_regression, io_loop, mock_clock, mocker, module_mocker, monkeypatch, no_cover, num_regression, nursery, original_datadir, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, requests_mock, session_mocker, shared_datadir, smart_caplog, subtests, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, tmpworkdir, twisted_greenlet, unused_tcp_port, unused_tcp_port_factory, virtualenv, weave, worker_id, workspace, xprocess
>       use 'pytest --fixtures [testpath]' for help on them.

/home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_debug.py:50
_______________________________________________________ ERROR at setup of test_httpretty_debugs_socket_recvfrom_into _______________________________________________________
file /home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_debug.py, line 83
  @skip('not currently supported')
  @httprettified
  @scenario(create_socket)
  def test_httpretty_debugs_socket_recvfrom_into(context):
E       fixture 'context' not found
>       available fixtures: _session_faker, _unused_port, anyio_backend, anyio_backend_name, anyio_backend_options, autojump_clock, base_url, benchmark, benchmark_weave, betamax_parametrized_recorder, betamax_parametrized_session, betamax_recorder, betamax_session, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, cov, current_cases, data_regression, datadir, dataframe_regression, doctest_namespace, event_loop, faker, faker_seed, file_regression, freezer, fs, http_client, http_port, http_server, https_client, https_port, https_server, image_regression, io_loop, mock_clock, mocker, module_mocker, monkeypatch, no_cover, num_regression, nursery, original_datadir, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, requests_mock, session_mocker, shared_datadir, smart_caplog, subtests, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, tmpworkdir, twisted_greenlet, unused_tcp_port, unused_tcp_port_factory, virtualenv, weave, worker_id, workspace, xprocess
>       use 'pytest --fixtures [testpath]' for help on them.

/home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_debug.py:83
__________________________________________________________________ ERROR at setup of test_recording_calls __________________________________________________________________
file /home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_requests.py, line 770
  @use_tornado_server
  def test_recording_calls(port):
E       fixture 'port' not found
>       available fixtures: _session_faker, _unused_port, anyio_backend, anyio_backend_name, anyio_backend_options, autojump_clock, base_url, benchmark, benchmark_weave, betamax_parametrized_recorder, betamax_parametrized_session, betamax_recorder, betamax_session, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, cov, current_cases, data_regression, datadir, dataframe_regression, doctest_namespace, event_loop, faker, faker_seed, file_regression, freezer, fs, http_client, http_port, http_server, https_client, https_port, https_server, image_regression, io_loop, mock_clock, mocker, module_mocker, monkeypatch, no_cover, num_regression, nursery, original_datadir, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, requests_mock, session_mocker, shared_datadir, smart_caplog, subtests, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, tmpworkdir, twisted_greenlet, unused_tcp_port, unused_tcp_port_factory, virtualenv, weave, worker_id, workspace, xprocess
>       use 'pytest --fixtures [testpath]' for help on them.

/home/tkloczko/rpmbuild/BUILD/HTTPretty-1.1.4/tests/functional/test_requests.py:770
============================================================================= warnings summary =============================================================================
tests/functional/test_urllib2.py::test_httpretty_should_allow_forcing_headers_urllib2
  /home/tkloczko/rpmbuild/BUILDROOT/python-httpretty-1.1.4-3.fc35.x86_64/usr/lib/python3.8/site-packages/httpretty/core.py:1034: UserWarning: HTTPretty got to register the Content-Length header with "'35a'" which is not a number
    warnings.warn(

tests/bugfixes/nosetests/test_430_respect_timeout.py::test_read_timeout
  /usr/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-1105

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/home/tkloczko/rpmbuild/BUILDROOT/python-httpretty-1.1.4-3.fc35.x86_64/usr/lib/python3.8/site-packages/httpretty/core.py", line 1133, in fill_filekind
      fk.write(utf8(item) + b'\n')
  ValueError: write to closed file

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
SKIPPED [1] ../../../../../usr/lib/python3.8/site-packages/_pytest/unittest.py:355: Skipped
SKIPPED [1] ../../../../../usr/lib/python3.8/site-packages/_pytest/unittest.py:355: no redis server available for test
ERROR tests/functional/test_bypass.py::test_disallow_net_connect_1
ERROR tests/functional/test_bypass.py::test_using_httpretty_with_other_tcp_protocols
ERROR tests/functional/test_bypass.py::test_httpretty_bypasses_a_unregistered_request
ERROR tests/functional/test_bypass.py::test_httpretty_bypasses_when_disabled
ERROR tests/functional/test_debug.py::test_httpretty_debugs_socket_recv_into
ERROR tests/functional/test_debug.py::test_httpretty_debugs_socket_send
ERROR tests/functional/test_debug.py::test_httpretty_debugs_socket_recvfrom
ERROR tests/functional/test_debug.py::test_httpretty_debugs_socket_sendto
ERROR tests/functional/test_debug.py::test_httpretty_debugs_socket_recvfrom_into
ERROR tests/functional/test_requests.py::test_recording_calls
========================================================= 11141 passed, 2 skipped, 2 warnings, 10 errors in 37.57s =========================================================
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
```

**Comment by kloczek** [comment]
After deselecting units causing errors there are saome pytest warnings
```consol
============================================================================= warnings summary =============================================================================
tests/bugfixes/nosetests/test_430_respect_timeout.py::test_read_timeout
  /usr/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-1004

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/home/tkloczko/rpmbuild/BUILDROOT/python-httpretty-1.1.4-3.fc35.x86_64/usr/lib/python3.8/site-packages/httpretty/core.py", line 1133, in fill_filekind
      fk.write(utf8(item) + b'\n')
  ValueError: write to closed file

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/functional/test_urllib2.py::test_httpretty_should_allow_forcing_headers_urllib2
  /home/tkloczko/rpmbuild/BUILDROOT/python-httpretty-1.1.4-3.fc35.x86_64/usr/lib/python3.8/site-packages/httpretty/core.py:1034: UserWarning: HTTPretty got to register the Content-Length header with "'35a'" which is not a number
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
SKIPPED [1] ../../../../../usr/lib/python3.8/site-packages/_pytest/unittest.py:355: no redis server available for test
SKIPPED [1] ../../../../../usr/lib/python3.8/site-packages/_pytest/unittest.py:355: Skipped
======================================================= 11142 passed, 2 skipped, 10 deselected, 2 warnings in 38.92s =======================================================
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
```

**Comment by kloczek** [comment]
Duplicated of #449.
Closing
