### ISSUE TITLE
Can't use file like object for data in python3

### ISSUE THREAD

**Issue by jamesls** [gabrielfalcao/HTTPretty#86]
I'm using requests and want to use httpretty for a PUT request that uses a file like object for the `data` arg.  This works in python2, but not in python3.

The following script works in python2:

```
import json
from pprint import pprint

import requests

import httpretty


def test_real():
    _test()

@httpretty.activate
def test_fake():
    httpretty.register_uri(httpretty.PUT, 'http://httpbin.org/put',
                           body='["foo"]', content_type='application/json')
    _test()


def _test():
    response = requests.put('http://httpbin.org/put',
                            data=open('/tmp/somefile.txt', 'rb'))
    print(response.status_code)
    pprint(json.loads(response.content.decode('utf-8')))


print("REAL:")
test_real()
print("\nFAKE:")
test_fake()
```

Running this in python3 with the latest httpretty/requests I get:

```
Traceback (most recent call last):
  File "/tmp/repro.py", line 29, in <module>
    test_fake()
  File ".virtualenvs/30299b7f43f6b05d/lib/python3.3/site-packages/httpretty/core.py", line 807, in wrapper
    return test(*args, **kw)
  File "/tmp/repro.py", line 16, in test_fake
    _test()
  File "/tmp/repro.py", line 21, in _test
    data=open('/tmp/somefile.txt', 'rb'))
  File ".virtualenvs/30299b7f43f6b05d/lib/python3.3/site-packages/requests/api.py", line 99, in put
    return request('put', url, data=data, **kwargs)
  File ".virtualenvs/30299b7f43f6b05d/lib/python3.3/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File ".virtualenvs/30299b7f43f6b05d/lib/python3.3/site-packages/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File ".virtualenvs/30299b7f43f6b05d/lib/python3.3/site-packages/requests/sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File ".virtualenvs/30299b7f43f6b05d/lib/python3.3/site-packages/requests/adapters.py", line 292, in send
    timeout=timeout
  File ".virtualenvs/30299b7f43f6b05d/lib/python3.3/site-packages/requests/packages/urllib3/connectionpool.py", line 428, in urlopen
    body=body, headers=headers)
  File ".virtualenvs/30299b7f43f6b05d/lib/python3.3/site-packages/requests/packages/urllib3/connectionpool.py", line 280, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python3/3.3.1/Frameworks/Python.framework/Versions/3.3/lib/python3.3/http/client.py", line 1061, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python3/3.3.1/Frameworks/Python.framework/Versions/3.3/lib/python3.3/http/client.py", line 1099, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python3/3.3.1/Frameworks/Python.framework/Versions/3.3/lib/python3.3/http/client.py", line 1057, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python3/3.3.1/Frameworks/Python.framework/Versions/3.3/lib/python3.3/http/client.py", line 906, in _send_output
    self.send(message_body)
  File "/usr/local/Cellar/python3/3.3.1/Frameworks/Python.framework/Versions/3.3/lib/python3.3/http/client.py", line 871, in send
    self.sock.sendall(data)
  File ".virtualenvs/30299b7f43f6b05d/lib/python3.3/site-packages/httpretty/core.py", line 235, in sendall
    requestline, _ = data.split(b'\r\n', 1)
AttributeError: '_io.BufferedReader' object has no attribute 'split'
```

**Comment by rm--** [comment]
I tried it with python `2.7.10` and python `3.4.3` and
```
httpretty==0.8.10
requests==2.7.0
```
and can't reproduce anymore.
So it could be closed.

**Comment by rolftimmermans** [comment]
I still get this error with `pypy3` (PyPy 2.4.0).
